name: Run Generator Pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - main
    paths:
      - "generator/*"
concurrency:
  group: "generator"
  cancel-in-progress: true
jobs:
  Build:
    name: Run Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Load secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Install uv (Auto-installs Python)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run Generator (Auto-installs dependencies)
        run: uv run generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
